services:
  mysql:
    image: mysql:8.0.44-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: document_management_system
      MYSQL_USER: doc-user
      MYSQL_PASSWORD: doc-user
    networks:
      - doc-backend-network
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:8.2.1
    ports:
      - "6379:6379"
    networks:
      - doc-backend-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - redis_data:/data

networks:
  doc-backend-network:
    name: doc-backend-network
  doc-frontend-network:
    name: doc-frontend-network

volumes:
  mysql_data:
  redis_data: