spring:
  application:
    name: document-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/document_management_system?createDatabaseIfNotExist=true
    username: root
    password: Nipun1234@#
  jpa:
    show-sql: true

security:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}