spring:
  application:
    name: document-management-system
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

security:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

cache:
  names:
    document:
      websocket:
        full-connection: DOCUMENT_CONNECTED_USERS_CACHE
        branch-connection:
          users: DOCUMENT_BRANCH_CONNECTED_USERS_CACHE
          sessions: DOCUMENT_BRANCH_CONNECTED_SESSIONS_CACHE
        permission: DOCUMENT_USER_PERMISSION_CACHE
        state: DOCUMENT_BRANCH_STATE_CACHE
        cache-ttl: 120
    user:
      websocket:
        user-connection:
          users: CONNECTED_USERS_CACHE
          sessions: CONNECTED_USERS_CACHE
        cache-ttl: 120

cloud:
  blob-storage:
    azure:
      endpoint: ${AZURE_BLOB_SERVICE_ENDPOINT}
      token: ${AZURE_BLOB_SERVICE_SAS_TOKEN}
      container: ${AZURE_BLOB_SERVICE_CONTAINER}

client:
  url: ${CLIENT_URL}