spring:
  application:
    name: document-management-system
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

security:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

cache:
  names:
    user:
      websocket:
        user-connection:
          users: CONNECTED_USERS_CACHE
          sessions: CONNECTED_USERS_CACHE
        cache-ttl: 120

cloud:
  blob-storage:
    azure:
      endpoint: ${AZURE_BLOB_SERVICE_ENDPOINT}
      token: ${AZURE_BLOB_SERVICE_SAS_TOKEN}
      container: ${AZURE_BLOB_SERVICE_CONTAINER}

client:
  url: ${CLIENT_URL}

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 10s
    instances:
      globalLimiter:
        baseConfig: default
